# -*- coding: utf-8 -*-
"""HomeworkLab2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NcRtdgKcAnva2TURIgYeXUKtfo7pBhaC

HOMEWORK LAB2 
NGUYEN VAN QUOC VIET_19522518
Github: https://github.com/vietkitoo/DataThucHanhLab2.git
"""

import pandas as pd
df = pd.read_csv('/content/sales.csv')
df.head()

df['name'] = df['name'].str.replace('"', '')
df['ordered_at'] = pd.to_datetime(df['ordered_at'])
df['price'] = df['price'].replace('[$,]', '', regex=True).astype(float)
df['line_total'] = df['line_total'].replace('[$,]', '', regex=True).astype(float)
print(df.dtypes)

df.drop_duplicates(inplace=True)

df.dropna(inplace=True)

df.head()

print(df['quantity'].describe())

print(df['price'].describe())

print(df['line_total'].describe())

print(df['name'].value_counts())

df.head()

import pandas as pd
data = pd.read_csv('/content/job-market.csv')
data.head(10)
data.info()
data.dropna(inplace=True)
data.drop_duplicates(inplace=True)

data['Id'] = data['Id'].astype(int)
data['LowestSalary'] = data['LowestSalary'].astype(float)
data['LowestSalary'] = pd.to_numeric(data['LowestSalary'], errors='coerce')
data['HighestSalary'] = data['HighestSalary'].astype(float)
data['HighestSalary'] = pd.to_numeric(data['HighestSalary'], errors='coerce')
data['Date'] = pd.to_datetime(data['Date'])

print(data.info())

print(data.describe())

print(data.isnull().sum())

data.head(10)